services:
  n8n:
    image: n8nio/n8n:${N8N_VERSION:?required}
    container_name: n8n
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./.docker/n8n/data:/home/node/.n8n
    networks:
      - traefik-network
      - postgres-network
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik-network

      # Router - restricted by IP
      - traefik.http.routers.n8n.rule=Host(`${N8N_SERVER_HOSTNAME:?required}`)
      - traefik.http.routers.n8n.entrypoints=websecure
      - traefik.http.routers.n8n.tls.certresolver=le-cloudflare
      - traefik.http.routers.n8n.middlewares=trusted@file
      - traefik.http.routers.n8n.service=n8n

      # Webhook Router - public
      - traefik.http.routers.n8n-webhook.rule=Host(`${N8N_SERVER_HOSTNAME:?required}`) && (PathPrefix(`/webhook/`) || PathPrefix(`/webhook-test/`))
      - traefik.http.routers.n8n-webhook.entrypoints=websecure
      - traefik.http.routers.n8n-webhook.tls.certresolver=le-cloudflare
      - traefik.http.routers.n8n-webhook.service=n8n

      # Service
      - traefik.http.services.n8n.loadbalancer.server.port=5678

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  traefik-network:
    external: true
  postgres-network:
    external: true
